# Generated by Django 3.0 on 2022-11-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                CREATE TABLE oc_lettings_site_address(
                     number int, 
                     street varchar(255),
                     city varchar(255),
                     state varchar(255),
                     zip_code int,
                     country_iso_code int 
                )
            """),
        migrations.RunSQL("""
                    CREATE TABLE oc_lettings_site_letting(
                        title varchar(255),
                        address_id int 
                    )
                """),
        migrations.RunSQL("""
                        CREATE TABLE  oc_lettings_site_profile(
                            user_id int,
                            favorite_city varchar(255)
                        )
                    """),
        migrations.RunSQL("""
            INSERT INTO lettings_address (
                 number, 
                 street,
                 city,
                 state,
                 zip_code,
                 country_iso_code   
            )
            SELECT
                 number, 
                 street,
                 city,
                 state,
                 zip_code,
                 country_iso_code 
            FROM
                oc_lettings_site_address;
            INSERT INTO lettings_letting (
                     title,
                     address_id  
                )
                SELECT
                     title,
                     address_id 
                FROM
                    oc_lettings_site_letting;       
        """, reverse_sql="""
            INSERT INTO oc_lettings_site_address(
                 number, 
                 street,
                 city,
                 state,
                 zip_code,
                 country_iso_code 
            )
            SELECT
                 number, 
                 street,
                 city,
                 state,
                 zip_code,
                 country_iso_code 
            FROM
                lettings_address;
            INSERT INTO oc_lettings_site_letting(
                     title,
                     address_id 
                )
                SELECT
                     title,
                     address_id 
                FROM
                    lettings_letting;
        """)]
