version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app -f ./Dockerfile .

      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run flake8
          command: flake8

workflows:
  sample:
    jobs:
      - build-and-test






