version: 2.1

jobs:
  build-and-test:
    executor:
      name: docker
      image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t my-app .
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run flake8
          command: flake8
      - run:
          name: Run the application
          command: |
            docker run -p 8000:8000 my-app
workflows:
  sample:
    jobs:
      - build-and-test



