version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@3.1.0

jobs:
  build-and-test:
    executor: docker/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - setup_remote_docker:
          version: 18.09.7
      - run:
          name: Build Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t my-app .
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run flake8
          command: flake8
      - run:
          name: Run the application
          command: |
            docker run -p 8000:8000 my-app
workflows:
  sample:
    jobs:
      - build-and-test
