version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    executor: python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Copy requirements
          command: cp requirements.txt /app/requirements.txt
      - run:
          name: Build the Docker image
          command: |
            docker build -t my-image .
      - run:
          name: Run the tests
          command: |
            docker run -v "$(pwd):/app" my-image pytest
            docker run -v "$(pwd):/app" my-image flake8

workflows:
  sample:
    jobs:
      - build-and-test
